name: state_machina
description: An incredibly simple state machine library for Flutter and other Dart applications.
homepage: https://github.com/granmoe/state_machina

version: 3.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  test: ^1.24.5
